server:
  port: 8889

spring:
  application:
    name: feign-client
  zipkin:
    enabled: true
    base-url: http://localhost:9411

eureka:
  instance:
    instance-id: eureka-ribbon-client
    appname: ${spring.application.name}
    #prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10097/eureka/

logging:
  level:
    com.shengsiyuan.feign.client.EurekaClientFeign: debug
